### ISSUE TITLE
Please support ${my-unset-var=default} ${my-empty-var:=default}

### ISSUE THREAD

**Issue by guettli** [icy/genvsub#10]
Please support 

```
${my-unset-var=default}
```

and 

```
${my-empty-var:=default}
```

Related: https://github.com/drone/envsubst#supported-functions

BTW, I prefer you tool, since you have the helpful `-u` option.

**Comment by icy** [comment]
Hi @guettli,

Thanks for your suggestion. It's great that you like my tool.

May I ask how you configure your variables? 

I often do that from the container shell which has quite a lot of builtin features, one of them is what you've suggested. The other may be: nested expansion, monkey-patching feature, ... My expectation is not to replace shell features. Otherwise it's quite possible that the tool ends up in having its own parsing support as you see in https://github.com/drone/envsubst/blob/master/parse/scan.go. 

Edit: typo fix.

**Comment by guettli** [comment]
Up to now we use this:

```
curl -sSL https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.3.0/cluster-api-components.yaml | envsubst | kubectl apply -f
```

and envsubst being from https://github.com/drone/envsubst

You can look at this file. 

I guess that this needs some kind of parsing.

**Comment by icy** [comment]
@guettli I will have a quick look if there is any _fast_ way. I believe I tried the feature in some local branch but I didn't continue to avoid the complexity of the code base ;) 

Regarding your pipeline, I'd suggest that using my tool (or similar) with `-u` would cause some unexpected output/result. This is because my tool (and also drone/envsubst [1]) is processing input line by line. If there is any problem on the fly, the tool can't _undo_ any output which has been shipped out to stdout device.

From my knowledge [2], a pipe-ware tool for your purpose would be the Rust version (https://github.com/gdvalle/envsub) which has buffering feature -- but I haven't tried it yet.

Another convenient tool for you is this https://github.com/a8m/envsubst (also mentioned in [2]), which has some capacity of `set -u` and with some basic shell feature (https://github.com/a8m/envsubst#docs). What do you think about this one?

[1] https://github.com/drone/envsubst/blob/master/cmd/envsubst/main.go#L16
[2] https://github.com/icy/genvsub#references

**Comment by guettli** [comment]
@icy thank you for pointing me to https://github.com/a8m/envsubst. It supports "failing on unset var" and "${foo:=bar}"

**Comment by guettli** [comment]
@icy feel free to close the issue.

**Comment by icy** [comment]
@guettli  That's good that you see a right tool for your purpose. I'm glad some initial idea helps. I would keep the issue open for a while, playing with some local code.
